config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  resources :post_tags
  resources :tags, only: [:show]
  resources :posts
  resources :searches

  resources :posts do
    resources :comments
  end

  resources :users
  resources :users do
    member do
      post 'follow'
      delete 'unfollow'
      get 'following'
      get 'followed'
    end
  end

  delete '/sessions/logout', to: 'sessions#logout', as: 'logout'
  get '/sessions/new', to: 'sessions#new', as: 'new_login'
  post '/sessions/create', to: 'sessions#create', as: 'login'

  put '/post/:id/like', to: 'posts#like', as: 'like'
  delete '/post/:id/like', to: 'posts#unlike', as: 'unlike'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  has_many :followeds, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :followed_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  validates :username, presence: { message: 'You need a username! How else will we know what to call you?' }
  validates :username, uniqueness: { message: 'Shoot! Someone is already using this username...' }
  has_attached_file :image,
                    default_url: ':style/missing_avatar.jpg',
                    styles: {
                      thumb: ['x300', :jpeg],
                      original: [:jpeg]
                    }

  validates_attachment :image,
                       content_type: { content_type: %r{\Aimage/.*\z} }

  has_secure_password

  def self.search(query)
    where('USERNAME like ?', "%#{query}%") if query.present?
  end

  def my_likes
    posts.map { |post| post.likes.count}
  end

  def num_likes
    my_likes.inject(0) { |sum, num| sum + num}
  end

  def top_five
    User.all.sort_by { |user| -user.num_likes}
  end

  def following_posts
    followers.map(&:posts).flatten
  end

  def following_and_self_posts
    following_posts + posts
  end

  def user_ids
    User.all.map(&:id)
  end

  def following_ids
    followers.map(&:id)
  end

  def not_following
    id_array = user_ids - following_ids - [id]
    id_array.map { |id| User.find(id)}
  end

  def following?(user)
    followers.include? user
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :find_user, except: %i[index new create]
  skip_before_action :authorized, only: %i[new create]

  def following
    @users = @user.followers
  end

  def followed
    @users = @user.followeds
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params(:username, :password, :password_confirmation, :image, :query))

    if @user.valid?
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @user.update(user_params(:username, :password, :password_confirmation, :image, :location, :query))
    session[:user_id] = @user.id
    if @user.valid?
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to new_user_path
  end

  def follow
    Relationship.create(follower: @user, followed: @current_user)
    redirect_to @user
  end

  def unfollow
    @relationship = Relationship.find_by(follower: @user, followed: @current_user)
    @relationship.destroy
    redirect_to posts_path
  end

  private

  def user_params(*args)
    params.require(:user).permit(*args)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, html: {class: "was-validated"} do |user_builder| %>
    <div class="form-group mt-4">
        <%= user_builder.label "Username" %>
        <%= user_builder.text_field :username, class: "form-control" %>
            <div class="invalid-feedback">
                <%= @user.errors[:username].join if @user.errors[:username].any? %>
            </div>
    </div>
    <div class="form-group">
        <%= user_builder.label "Profile Picture" %><br>
        <%= user_builder.file_field :image %>
    </div>
    <div class="form-group">
        <%= user_builder.label "Location" %>
        <%= user_builder.text_field :location, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= user_builder.label "Password" %>
        <%= user_builder.text_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= user_builder.label "Confirm Password" %>
        <%= user_builder.text_field :password_confirmation, class: "form-control" %>
        <div class="invalid-feedback">
            <%= @user.errors[:password_confirmation].join if @user.errors[:password_confirmation].any? %>
        </div>
        <%= user_builder.submit "Update Profile", class: "btn btn-primary btn-lg mt-5 btn-block" %>
    </div>
<% end %>

<div class="settings-form">
    <%= button_to "Delete Account", user_path(@user), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-lg mt-3 btn-block"%>
</div>

app/views/users/edit.html.erb
<div class="container mt-4 mb-4">
  <div class="row">
    <div class="col-6">
      <h2>Settings</h2>
      <h4>Update Your Profile Here!</h4>
      <%= render 'form', submit_text: 'Update' %>
    </div>
  </div>
</div>

app/views/users/followed.html.erb
<div class="container mt-4 mb-4">
  <div class="row">
    <div class="col-6">
      <h2><%= @user.username %> is followed by...</h2>
        <% if @users.any? %>
          <ul class="list-group">
            <% @users.each do |user| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <%= link_to image_tag(user.image.url(:original), class: "show-pic mx-autp"), user_path(user) %><%= link_to user.username, user_path(user)%>
                <span class="badge badge-primary badge-pill"><%= user.posts.count %> posts</span>
              </li>
            <% end %>
          </ul>
        <% else %>
          <h5>No one yet... Get out there and find some Cuties!</h5>
        <% end %>
    </div>
  </div>
</div>

app/views/users/following.html.erb
<div class="container mt-4 mb-4">
  <div class="row">
    <div class="col-6">
      <h4><%= @user.username %> is following...</h4>
      <% if @users.any? %>
        <ul class="list-group">
          <% @users.each do |user| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <%= link_to image_tag(user.image.url(:original), class: "show-pic mx-autp"), user_path(user) %><%= link_to user.username, user_path(user)%>
              <span class="badge badge-primary badge-pill"><%= user.posts.count %> posts</span>
            </li>
          <% end %>
        </ul>
      <% else %>
        <h5>No one yet... Get out there and find some Cuties!</h5>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="search-results">
<h2>Your search results: </h2>

<% if @users %>
    <% @users.each do |user| %>
        <p><%= link_to user.username, user_path(user) %> - <%= user.posts.count %><%= " post".pluralize(user.posts.count) %> </p>
    <% end %>
<% end %>
</div>

app/views/users/new.html.erb
<%= render 'shared/background' %>
<div class="home">
  <div class="jumbotron signup">
    <div class="row">
      <div class="col">
        <h1 class="display-3">Welcome to CutieGram!</h1>
        <h4>Upload your pictures and share them with your friends.</h4>
      </div>

      <div class="col">
        <%= form_for @user, html: {class: "was-validated"} do |user_builder| %>
          <div class="form-group">
              <%= user_builder.label :username %>
              <%= user_builder.text_field :username, class: "form-control" %>
              <div class="invalid-feedback">
                <%= @user.errors[:username].join if @user.errors[:username].any? %>
              </div>
          </div>

          <div class="form-group">
              <%= user_builder.label :password %>
              <%= user_builder.password_field :password, class: "form-control" %>
              <div class="invalid-feedback">
                <%= @user.errors[:password].join if @user.errors[:password].any? %>
              </div>
          </div>

          <div class="form-group">
              <%= user_builder.label :password_confirmation %>
              <%= user_builder.password_field :password_confirmation, class: "form-control" %>
              <div class="invalid-feedback">
                <%= @user.errors[:password_confirmation].join if @user.errors[:password_confirmation].any? %>
              </div>
          </div>
            <%= user_builder.submit 'Sign Up', class: "btn btn-primary btn-lg" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="border-bottom border-secondary mx-auto modal-dialog-centered show-profile-header row" style="width: 40%">
  
      <%= image_tag(@user.image.url(:original), class: "show-page-pic mr-5") %>


  <div class="show-profile-pic">
    <div class="row">
      <h2 class="card-title"> <%= @user.username %> </h2>
      <% if @current_user.following?(@user) %>
        <%= button_to 'Unfollow', unfollow_user_path(@user), method: :delete, class: "btn btn-primary ml-5" %>
      <% elsif @current_user != @user %>
        <%= button_to 'Follow', follow_user_path(@user), class: "btn btn-primary ml-5" %>
      <% end %>
    </div>
    <div class="row mt-2">
      <h5 class="ml-2 mr-1"><strong><%= @user.posts.count %></strong><%=" post".pluralize(@user.posts.count)%></h5>
      <h5 class="ml-1 mr-1"><strong><%= link_to "#{@user.followeds.count} follower".pluralize(@user.followeds.count), followed_user_path(@user) %></strong></h5>
      <h5 class="ml-1 mr-1"><strong><%= link_to "#{@user.followers.count} following", following_user_path(@user) %></strong></h5>
    </div>
    <div class="profile-name">
      <% if @user.location.present? %>
        <h5 class="mt-2 mr-3"><i class='fas fa-map-marker-alt mr-2' style='font-size:21px'></i><%= link_to @user.location, "http://www.google.com/maps/place/#{@user.location}", target: :_blank %></h5>
      <% end %>
      <h6 class="card-title mt-3 ml-1"> <%= @user.num_likes %><%= " like".pluralize(@user.num_likes) %> total </h6>
    </div>
    <div class="followers-list">
      <% if @user.followeds.any? %>
        <p>Followed by </p>
        <% counter = 0 %>
        <% counter2 = 0%>
        <% @user.followeds.each do |user| %>
            <% if counter < 2 %>
            <p class="ml-1"> <%= link_to user.username, user_path(user)%><%= ", "%> </p>
            <% elsif counter == 2 %>
              <p class="ml-1"> <%= link_to user.username, user_path(user)%><%= " "%> </p>
            <% else %>
              <% if @user.followeds.count > 3 %>
                <% if counter2 == 0 %>
                  <p class="ml-1"><%= " and #{@user.followeds.count-3} others." %></p>
                  <% counter2 += 1%>
                <% end %>
              <% end %>
            <% end %>
            <% counter += 1%>
        <% end %>
      <% else %>
        <p>You have no followers yet</p>
      <% end %>
    </div>
  </div>


    

    
</div>
<div class="container mt-5 user-show-images">
  <div class="row">
    <% @user.posts.order('created_at DESC').each do |post| %>
      <%if post.image.exists?%>
        <div class="col-sm-4 mb-4">
          <%= link_to (image_tag(post.image.url(:original), class: "card-img-top show")), post_path(post) %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>