config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  resources :post_tags
  resources :tags, only: [:show]
  resources :posts
  resources :searches

  resources :posts do
    resources :comments
  end

  resources :users
  resources :users do
    member do
      post 'follow'
      delete 'unfollow'
      get 'following'
      get 'followed'
    end
  end

  delete '/sessions/logout', to: 'sessions#logout', as: 'logout'
  get '/sessions/new', to: 'sessions#new', as: 'new_login'
  post '/sessions/create', to: 'sessions#create', as: 'login'

  put '/post/:id/like', to: 'posts#like', as: 'like'
  delete '/post/:id/like', to: 'posts#unlike', as: 'unlike'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :likes, dependent: :destroy

  validates :description, presence: { message: 'Post needs a description!' }
  validates :image, presence: { message: 'Post needs an image!' }
  has_attached_file :image,
                    styles: {
                      thumb: ['x300', :jpeg],
                      original: [:jpeg]
                    }
  validates_attachment :image,
                       content_type: { content_type: %r{\Aimage/.*\z} }

  def liked?(user)
    !!likes.find { |like| like.user_id == user.id}
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :find_post, only: %i[show edit update destroy like]

  def index
    @posts = current_user.following_and_self_posts.sort_by(&:created_at).reverse
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params(:description, :image))

    if @post.save
      TagGenerator.call(@post, params[:post][:image])
      redirect_to @post
    else
      render :new
    end
  end

  def update
    if @post.update(post_params(:description))
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    user = @post.user
    @post.destroy
    redirect_to user_path(user)
  end

  def like
    @post = Post.find(params[:id])
    Like.create(user_id: @current_user.id, post_id: @post.id)
    redirect_to post_path(@post)
  end

  def unlike
    @post = Post.find(params[:id])
    like = Like.find_by(user_id: @current_user.id, post_id: @post.id)
    like.destroy
    redirect_to post_path(@post)
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params(*args)
    params.require(:post).permit(*args)
  end
end

app/views/posts/edit.html.erb
<div class="container new-post">
  <h3 class="display-4 text-center mt-5">How would you like to edit?</h3>
  <div id="new-post-form">
    <%= form_for @post, html: {class: "was-validated"} do |f| %>
      <div class="mt-3 mb-3">
        <%= f.text_area :description, placeholder: "Write a caption...", class: "form-control is-invalid" %>
        <div class="invalid-feedback">
          <%= @post.errors[:description].join if @post.errors[:description].any? %>
        </div>
      </div>

      <%= f.submit "Post", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col">
            <% if @posts.blank? %>
                <div class="mt-4">
                    <h5>Either you're not following anyone, or they just haven't posted anything yet.</h5>
                    <h5>Maybe these tags will give you some ideas!</h5>
                    <% Tag.random_five_tags.each do |tag| %>
                        <%= link_to '#' + tag.name, searches_path(query: tag.name), class: "btn btn-outline-secondary mt-2" %>
                    <% end %>
                </div>
            <% else %>
                <% @posts.each do |post| %>
                    <% if post.image.exists? %>
                        <div class="card" style="width: 30rem">
                            <div class="card-body">
                                <%= link_to (image_tag(post.image.url(:original), class: "card-img-top m-1")), post_path(post)%>
                            </div>
                            <div class="card-footer">
                                <%= image_tag(post.user.image.url(:original), class: "show-pic mr-2") %>
                                <span class="card-text font-weight-bold"><%=link_to post.user.username, user_path(post.user)%></span>
                                <p class="card-text mt-3"><%=post.description%></p>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            <% end %>
        </div>
        <div class="col">
            <div class="profile-pic">
                <%= link_to image_tag(current_user.image.url(:original), class: "show-pic"), current_user %>
                <% if current_user.location.present? %>
                    <h4><i class='fas fa-map-marker-alt mr-1' style='font-size:17px'></i><%= link_to current_user.location, "http://www.google.com/maps/place/#{current_user.location}", style: "font-size: 17px", target: :_blank %></h4>
                <% end %>
            </div>
            <div class="profile-name">
                <div class="float-left ml-2">
                    <h3 class="card-title"> <%= link_to current_user.username, current_user%> </h3>
                </div>
                <div class="float-right ml-5">
                    <h5 class="card-title mt-1"> <%= current_user.num_likes %><%= " like".pluralize(current_user.num_likes) %> total </h5>
                </div>
            </div>
            <div class="top-five">
                <h3 class="border-bottom border-primary mt-5 mb-4">Recommended Cuties for you to follow!</h3>
                <% current_user.not_following.sample(5).each do |user| %>
                    <div class="row mt-2 position-relative">
                        <%= link_to image_tag(user.image.url(:original), class: "show-pic"), user %>
                        <div class="mt-2 ml-2">
                            <h5><strong><%= link_to user.username, user %></strong> - <%= user.posts.count %> <%= " post".pluralize(user.posts.count) %></h5>
                        </div>
                        <%= button_to 'Follow', user, class: "btn btn-primary ml-5 btn-sm" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="container mt-4">
  <h2>Create your super cute post here, friend!</h2>
  <div id="new-post-form">
    <%= form_for @post, html: {class: "was-validated"} do |f| %>
      <div class="custom-file">
        <%= f.file_field :image %>
        <div class="invalid-feedback">
          <%= @post.errors[:image].join if @post.errors[:image].any? %>
        </div>
      </div>

      <div class="mt-3 mb-3">
        <%= f.text_area :description, placeholder: "Write a caption...", class: "form-control" %>
        <div class="invalid-feedback">
          <%= @post.errors[:description].join if @post.errors[:description].any? %>
        </div>
      </div>

      <%= f.submit "Post", class: "btn btn-primary btn-lg" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
    <div class="card mb-3 mx-auto border-dark" style="max-width: 50vw">
      <div class="row no-gutters">
        <div class="col-md-6 flex-this">
          <%= image_tag(@post.image.url(:original), class: "card-img show-img m-0")%>
        </div>
        <div class="col-md-6 flex-this">
          <div class="card-body">
            <div class="border-bottom border-secondary card-top">
                <% if @post.user.image.exists?%>
                  <%= link_to image_tag(@post.user.image.url(:original), class: "show-pic"), user_path(@post.user) %>
                <% end %>
              <div class="name-description">
                <div class="date-posted">
                  <h4 class="card-title card-head"><%= link_to @post.user.username, user_path(@post.user) %></h4><p class="card-head" style="font-size: 15px;"><%= "🗓️ #{@post.created_at.strftime("%B %d, %Y at %I:%M %p")}" %></p>
                </div>
                <p><%= @post.description %></p>
              </div>
            </div>
            <div class="border-bottom border-secondary comments" >
              <h5 class="mt-1">Comments:</h5>
                <ul>
                  <% if @post.comments.blank? %>
                  <li>
                    <p class="card-text">Thers are no comments yet.</p>
                  </li>
                  <% else %>
                      <% @post.comments.each do |comment| %>
                        <li>
                          <strong><p class="card-text"><%= link_to comment.user.username, user_path(comment.user) %></p></strong>  <p><%= comment.content %></p>
                        </li>
                      <% end %>
                  <% end %>
                </ul>
            </div>
            <div class="likes mt-3">
              <% if @post.liked?(@current_user) %>
                <%= button_to "♡", like_path(@post), method: :delete, class: "btn emoji-btn" %>
              <% else %>
                <%= button_to "💚", like_path(@post), method: :put, class: "btn emoji-btn" %>
              <% end %>
              <p class="ml-1 mb-0">Liked by: <%= @post.likes.count %><%=" person".pluralize(@post.likes.count)%> </p>
            </div>
            <div class="comment-form">
              <%= form_for [@post, Comment.new] do |f| %>
                <%= f.text_area :content, placeholder: "Make a comment", class: "mt-5" %>
                <%= f.submit 'Comment', class: "btn btn-primary mb-5" %>
              <% end %>
            </div>
            <div class="tags">
              <% @post.tags.each do |tag| %>
                <p><%= link_to "##{tag.name}", tag_path(tag) %> </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <% if @post.user == @current_user %>
      <div class="footer">
        <%= button_to 'Edit Post', edit_post_path(@post), method: :get, class: "bottom-buttons btn btn-primary" %>
        <%= button_to 'Delete Post', post_path(@post), method: :delete, class: "bottom-buttons btn btn-danger" %>
      </div>
    <% end %>