config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  resources :post_tags
  resources :tags, only: [:show]
  resources :posts
  resources :searches

  resources :posts do
    resources :comments
  end

  resources :users
  resources :users do
    member do
      post 'follow'
      delete 'unfollow'
      get 'following'
      get 'followed'
    end
  end

  delete '/sessions/logout', to: 'sessions#logout', as: 'logout'
  get '/sessions/new', to: 'sessions#new', as: 'new_login'
  post '/sessions/create', to: 'sessions#create', as: 'login'

  put '/post/:id/like', to: 'posts#like', as: 'like'
  delete '/post/:id/like', to: 'posts#unlike', as: 'unlike'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cutiegram</title>
    <%= csrf_meta_tags %> <%= csp_meta_tag %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://fonts.googleapis.com/css2?family=Oleo+Script&display=swap" rel="stylesheet">
    <%= favicon_link_tag asset_path('camera.png') %>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
      <% if @current_user %>
        <a class="navbar-brand" href="/posts"><%=image_tag("camera.png")%>Cutiegram</a>
      <% else %>
        <a class="navbar-brand" href="/users/new"><%=image_tag("camera.png")%>Cutiegram</a>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <% if @current_user %>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Hi @<%= @current_user.username %></a><span class="nav-text">
            </li>
            <li class="nav-item">
              <%= link_to 'My page', user_path(@current_user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/posts/new">New Post</a>
            </li>
            <li class="nav-item">
              <%= link_to "Settings", edit_user_path(@current_user), class: "nav-link"%>
            </li>
          </ul>
          <%= form_tag searches_path, :method => 'get', :class => "form-inline my-2 my-lg-0" do %>
            <%= text_field_tag :query, params[:query], class: "form-control mr-sm-2", placeholder:"Search" %>
            <%= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
          <% end %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to 'Logout', logout_path, method: 'delete', data: { confirm: "Logout?" }, class: "nav-link" %></li>
          </ul>
        <% else %>
          <ul class="navbar-nav mr-auto">
              <li class="nav-item"><%= link_to 'Sign up', new_user_path, method: 'get', class: "nav-link" %></li>
              <li class="nav-item"><%= link_to 'Login', new_login_path, class: "nav-link" %></li>
          </ul>
        <% end %>
      </div>
    </nav>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  
    <%= yield %>

  </body>
</html>